### ISSUE TITLE
iPhone X的bug

### ISSUE THREAD

**Issue by touchPython** [luckyxiangfeng/ZMCommentView#1]
已更新到最新, iPhone X下多点击几下评论框就会飞到最上面.
![1ef05d79-97fd-417d-87cc-166ff8fe5830](https://user-images.githubusercontent.com/25842665/45414211-73036580-b6ad-11e8-95ae-fb275041bc91.png)

**Comment by blmyself** [comment]
同样遇到了

**Comment by luckyxiangfeng** [comment]
> 同样遇到了

修复了。谢谢提醒。已经更新了最新版本

**Comment by luckyxiangfeng** [comment]
> 已更新到最新, iPhone X下多点击几下评论框就会飞到最上面.
> ![1ef05d79-97fd-417d-87cc-166ff8fe5830](https://user-images.githubusercontent.com/25842665/45414211-73036580-b6ad-11e8-95ae-fb275041bc91.png)谢谢提醒，已经更新最新版本了
