### ISSUE TITLE
获取不到输入的评论内容

### ISSUE THREAD

**Issue by 781400384** [luckyxiangfeng/ZMCommentView#10]
获取不到封装的textview上面的内容？这个怎么调用

**Comment by luckyxiangfeng** [comment]
很简单啦，我帮你加上去了，你拉一下最新代码即可

**Comment by 781400384** [comment]
感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lucky_feng"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 下午3:31
收件人: "luckyxiangfeng/ZMCommentView"<ZMCommentView@noreply.github.com&gt;; 
抄送: "┎ 纪先生丶"<781400384@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [luckyxiangfeng/ZMCommentView] 获取不到输入的评论内容 (#10)




很简单啦，我帮你加上去了，你拉一下最新代码即可
