### ISSUE TITLE
replyContentCell最多就显示一条吗

### ISSUE THREAD

**Issue by ZhangZhaoYuan** [luckyxiangfeng/ZMCommentView#5]
对于A评论，用户B回复A评论，调用replyContentCell，如果有用户C再回复B或者C回复A，在replyContentCell没有做处理吗？

**Comment by luckyxiangfeng** [comment]
这个处理很简单的，你可以自己扩展一下，模拟数据

**Comment by SUWW** [comment]
对于A评论，用户B回复A评论，调用replyContentCell，如果有用户C再回复B或者C回复A。如何做的？

**Comment by luckyxiangfeng** [comment]
如果你需要做成多级回复的话，可以改一下tableview为section 的形式去做。可以做成多级的

**Comment by SUWW** [comment]
如有时间，希望有一个完整的多级评论案例的，我有写了section的，但是可能是我技术问题，总感觉有点问题。。来自渣渣的呼唤。
