### ISSUE TITLE
评论cell添加点击回调弹出输入框 连续多次点击会crash

### ISSUE THREAD

**Issue by Bob-GGB** [luckyxiangfeng/ZMCommentView#7]

**Comment by luckyxiangfeng** [comment]
crash 截图发看一下，我没有测试出来crash

**Comment by Bob-GGB** [comment]
这是我在ZMCusCommentListView 的didSelectRowAtIndexPath方法写的block(https://user-images.githubusercontent.com/20783580/58141752-03e80300-7c77-11e9-972f-b861b0484cee.png)
这是在ZMCusCommentView的回调(https://user-images.githubusercontent.com/20783580/58141852-5f19f580-7c77-11e9-979c-5df8975b7e77.png)
断点走到showTextView的方法就Crash了 这是Crash的地方(https://user-images.githubusercontent.com/20783580/58141908-a7391800-7c77-11e9-9e29-65ac16d2b853.png)

**Comment by luckyxiangfeng** [comment]
看到这个问题了，快速点击cell,导致多次执行弹出键盘操作，键盘快速多次弹出多次导致的问题。已更新，修复快速多次点击cell，导致闪退的问题

**Comment by luckyxiangfeng** [comment]
修复
